### ISSUE TITLE
大神, 摩拜的 扫一扫怎么添加

### ISSUE THREAD

**Issue by okerivy** [ChengLuffy/app-Prefs#7]
摩拜的urlscheme 是 mobike
里面有个3dtouch 的 shortcutitems 是 scanqr
但是 好像打不开

**Comment by ChengLuffy** [comment]
mobike://scanqr

**Comment by okerivy** [comment]
good!

再问一下, 您的这个app自己的 URLSchemes 是什么? FastOpenJSON 貌似也可以打开,但是会调到一个错误页面

**Comment by ChengLuffy** [comment]
我没有开放这个，还么有想好这个的具体场景

**Comment by ChengLuffy** [comment]
### 新版本添加了几个 URL Schemes:
- shortcuts://list
- shortcuts://cache
- shortcuts://new
- shortcuts://                                      (不指定页面跳转)
